services:
  db:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - ossacra-back-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Servicio API
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_EXPIRES_IN: 1h
      JWT_REFRESH_EXPIRES_IN: 7d
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 465
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      PASSWORD_RESET_URL: https://cartilla.ossacra.com.ar/
      CORS_ORIGINS: ${CORS_ORIGINS}
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - ossacra-back-network
      - ossacra-front-network

  # Servicio Cliente
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
      - VITE_API_URL=${API_URL}
    restart: unless-stopped
    depends_on:
      - api
    environment:
      VITE_API_URL: ${API_URL}
    ports:
      - "8090:80"
    networks:
      - ossacra-front-network

networks:
  ossacra-back-network:
    driver: bridge
    internal: true
  ossacra-front-network:
    driver: bridge

volumes:
  mysql_data: